[GENERAL]
GENOME_TOOLS_PATH = ""
HOME_DIR = ""
delete_existing_species_home = true

[[INPUT]]
genomes_path = ""
genome_id = ""
species = ""
genome_size = 0
LTRHARVEST_INPUT_FASTA_FP = ""
SUFFIXERATOR_INDEX = ""

[TOOLS]

[TOOLS.ltrharvest]
index = "undefined"
range = "0 0"
seed = "30"
minlenltr = "100"
maxlenltr = "1000"
mindistltr = "1000"
maxdistltr = "15000"
similar = "85.00"
mintsd = "4"
maxtsd = "20"
motif = "undefined"
motifmis = "4"
vic = "60"
overlaps = "best"
xdrop = "5"
mat = "2"
mis = "-2"
ins = "-3"
del = "-3"
v = "no"
tabout = "yes"
seqids = "no"
md5 = "no"
longoutput = "no"
out = "undefined"
outinner = "undefined"
gff3 = "undefined"
help = "NO_ARGS"
"help+" = "NO_ARGS"
version = "NO_ARGS"

[TOOLS.suffixerator]
ssp = "yes"
des = "yes"
sds = "yes"
md5 = "yes"
clipdesc = "no"
sat = "undefined"
dna = "no"
protein = "no"
indexname = "undefined"
db = "NO_ARGS"
smap = "undefined"
lossless = "no"
mirrored = "no"
pl = "0"
dc = "0"
spmopt = "0"
memlimit = "undefined"
kys = "nosort"
dir = "fwd"
suf = "no"
lcp = "no"
bwt = "no"
bck = "no"
v = "no"
showprogress = "no"
ii = "undefined"
help = "NO_ARGS"
"help+" = "NO_ARGS"
version = "NO_ARGS"
